### ISSUE TITLE
Sorting file list also sorts [..] to somewhere

### ISSUE THREAD

**Issue by tricktresor** [tricktresor/zapcommander#1]
file list can be sorted (ALV grid).
The "directory up" line should be on top.

**Comment by hansstangl1** [comment]
In my words: ALV is in a container and so sorting is working by events of container and not by user_command of dynpro 110. Sorting is done by form fb_outtab_sort_ext in Fuba K_KKB_OUTTAB_SORT_EXT. 
table t_outtab is sorted by it_sort.
Only way I see currently, if you would have got column fieltyp of t_outtab in Dynpro, you could sort by filetyp down SPOS 01 and shortname up SPOS 02.
In Filetype you have got up for [..] and DIR for folders and empty for all other rows. Currntly filetype is not accessable (I assume technical).

**Comment by hansstangl1** [comment]
Structure ZAPCMD_FILE_DESCR has got filetype. in ZAPCMD_CL_FILELIST/Show I can change filetype to be visible. (WHEN 'FILETYPE' added). But I have to sort ALV now filetype desc and shortname asc. And ALV cannot sort differently for 2 columns...

**Comment by christianguenter2** [comment]
@hansstangl1 there's already a pull request open for this issue. https://github.com/tricktresor/zapcommander/pull/8
Maybe you can help test and review?

**Comment by hansstangl1** [comment]
Dear Christian.

I would like to help.

As mentioned I currently try abapgit with offline project and import zip files, as far as I think. Hopefully I have got some results tomorrow, it depends on workload in company.

I am not sure, wheter I can test a branch. I would need to create a zip file for all the changes. Is that possible, too?

 

br

Hans

 

 
 

Gesendet: Montag, 30. Mai 2022 um 16:16 Uhr
Von: "Christian Günter" ***@***.***>
An: "tricktresor/zapcommander" ***@***.***>
Cc: "hansstangl1" ***@***.***>, "Mention" ***@***.***>
Betreff: Re: [tricktresor/zapcommander] Sorting file list also sorts [..] to somewhere (#1)


 

@hansstangl1 there's already a pull request open for this issue. #8
Maybe you can help test and review?

**Comment by christianguenter2** [comment]
Yes, it's possible to import branches via offline repositories. Just go to the pull request and open the branch and then download the ZIP and proceed as usual.
E.g. this is the branch of my pull request https://github.com/christianguenter2/zapcommander/tree/sort
