### ISSUE TITLE
"GF_COMMANDER->CF_ACTIVELIST" is not compatible with the type of the reference to "LF_ACTIVELIST".

### ISSUE THREAD

**Issue by pooyoukun** [tricktresor/zapcommander#11]
Hello,
I am having an issue when activating the project after pulling it with a zip file through abapGit. In the report ZAPCMD_SAPCOMMANDER,  at line 65, the raised error when compiling is «"GF_COMMANDER->CF_ACTIVELIST" is not compatible with the type of the reference to "LF_ACTIVELIST".»
`DATA cf_activelist TYPE REF TO zapcmd_cl_filelist.`
while
```
DATA lf_activelist TYPE REF TO zapcmd_refref_filelist.
GET REFERENCE OF gf_commander->cf_activelist INTO lf_activelist.`
```
Our system is on S4CORE 106 patch 0001.
![image](https://user-images.githubusercontent.com/67104482/180719902-0a6fe420-4000-432f-8fa8-79743866827c.png)

Can you help me on that?
Thank you!

**Comment by Ennowulff** [comment]
puh... interesting... i have no idea so far. sorry.

**Comment by pooyoukun** [comment]
Strangely, the issue self-solved when activating the report separately from the rest of the project, and object by object.
