### ISSUE TITLE
dumps on startup on 731

### ISSUE THREAD

**Issue by AndreaBorgia-Abo** [tricktresor/zapcommander#14]
At "create object", dump with syntax error because of missing message-id.

```
  METHOD zapcmd_if_factory~create_dir.

    IF i_fcode = 'FRONTEND'.

      CREATE OBJECT eo_dir TYPE zapcmd_cl_frontend_dir.
      eo_dir->init( pf_full_name = i_dir ).

    ENDIF.
  ENDMETHOD.
```

If I perform the recommended extended syntax check, it comes back clean.
I can run it just fine on my two (much newer) MiniSAPs (A4H and NPL) but also in my previous job it ran fine on a 740 system.

**Comment by Ennowulff** [comment]
I cannot reproduce the dump as I do not have access to a 7.31 release.
I'll set min release to 7.40 -😉

**Comment by AndreaBorgia-Abo** [comment]
Revisiting this old issue: we'd like to use internally and are willing to do the adaptation work / PR, but first I wanted to run it by you.
Would you be ok with having an older target release?

**Comment by christianguenter2** [comment]
Sure go ahead.
Do you know ZAL11? It's quite similar to ZAPCOMMANDER and most likely 731 compatible. Maybe that's an alternative for you and can save some work.
https://community.sap.com/t5/application-development-blog-posts/zal11-a-replacement-for-al11/ba-p/12919249
But it's afaik not (yet) available via abapGit.

**Comment by AndreaBorgia-Abo** [comment]
Thanks for the tip, we'll have a look at both options.
FYI ZAL11 has a [repo](https://github.com/MikeSidorochkin/ZAL11), not sure if official though.

**Comment by AndreaBorgia-Abo** [comment]
@christianguenter2 #15 is ready but it is throwing some linting errors... was linting activated after the first push?

**Comment by Ennowulff** [comment]
I have switched off abapLint
