### ISSUE TITLE
language change / integration

### ISSUE THREAD

**Issue by AndreaBorgia-Abo** [tricktresor/zapcommander#9]
Ok, first thing first: project is BEYOND cool!

Next, those who understood what they were seeing complained about this being only in German (no problem for me, I understand it) and D is actually the original language for the various objects.

Couple of questions:
1. would it make sense to switch the main language to E? It should make it easier to contribute.
2. once that question is settled, is there an interest for English / Italian translations? I'm volunteering for those.

**Comment by christianguenter2** [comment]
I'd say yes, we should switch main language to english.

**Comment by AndreaBorgia-Abo** [comment]
Working with a local package on the NPL demo, I added the translation for the description of ZAPCMD_TBL_CHAR ("table with strings"), saved it, checked it was completely translated (easy: only one string) and switched the main language for the object.

SE80 confirms it is now EN but ababGit does not pick it up. I vaguely remember that on real systems the translations should be done last after releasing the transport: does this mean I cannot use a local package? In that case I'd rather use the A4H docker image and throw it away afterwards.

**Comment by christianguenter2** [comment]
I guess you need to change the main language of the repository to EN so abapGit detects it. Meaning we have to change main language of the repo and all objects in one go.

**Comment by AndreaBorgia-Abo** [comment]
I'll make some tests and let you know; ideally I want to preserve all existing texts, simply swapping them.

**Comment by AndreaBorgia-Abo** [comment]
I was going to complete the missing translations, then switch the language for each object, as SAP requires. Even after creating a normal (non local) package and locking everything in a CR, then changing the original language, abapGit still sees no changes in the affected object. And this apparently cannot be done, at least [abapGit doesn't do translations, yet](https://github.com/abapGit/abapGit/issues/2539)

One alternative approach would be to hand-edit the XML files changing the SPRSL tag and the relevant descriptions, but this would mean ditching all original German texts, without the possibility of storing additional languages in the repo.

Are you guys ok with it? May I proceed?

**Comment by Ennowulff** [comment]
done

**Comment by AndreaBorgia-Abo** [comment]
@Ennowulff with plain git and a text editor, I suppose, right?

**Comment by Ennowulff** [comment]
SAP functionality "change master language" for objects and manual edit of [.abapgit.xml](https://github.com/tricktresor/zapcommander/blob/master/.abapgit.xml)

**Comment by AndreaBorgia-Abo** [comment]
Of course :)
I was still thinking about the dual language and forgot about it, thanks.

**Comment by Ennowulff** [comment]
I think, you can now upload the italian translation. I would not recommend a direct edit of the xml files... ;)

**Comment by AndreaBorgia-Abo** [comment]
did you check the abapgit bug I linked above? what's your take on it?
if all is good, I'll try it in the coming days.

**Comment by Ennowulff** [comment]
argh. no, sorry. wasn't aware of that...

**Comment by christianguenter2** [comment]
Master language is still 'D'?
https://github.com/tricktresor/zapcommander/blob/42053b1c7b617f92572efe4dad028efb9c7dc86e/.abapgit.xml#L5

**Comment by Ennowulff** [comment]
Then the push changed it back to D… 🧐 will change it again asap.

**Comment by Ennowulff** [comment]
now it should be EN

**Comment by christianguenter2** [comment]
Great. Thx. 
LGTM. Closing.

**Comment by AndreaBorgia-Abo** [comment]
I can confirm the language is now E, the Italian translation will have to wait until abapGit handles them.
